name: Bandit

on: [push]

jobs:
  bandit-check:
    runs-on: ubuntu-latest
    name: Bandit Check
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Lint
        uses: jpetrucciani/bandit-check@master
        with:
          bandit_flags: "--skip B605,B607,B311"
